spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/security-study?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password:

  session:
    store-type: redis



logging:
  level:
   indi.qiaolin.security: debug

# 不启用权限认证
# security:
#   basic:
#     enabled: false


qiao:
  security:
    browser:
#      login-page: /demo-sigin.html
#      loginType: REDIRECT
      sign-up-url: /demo-signUp.html
      sign-out-url: /demo-signOut.html
      session:
        sessionInvalidUrl: /sessionInvalid
    code:
      image:
        width: 100
#        height:
        length: 2
#        expire-time:
#        url: /hello,/hello/*

    social:
       filter-process-url: /qqLogin
       qq:
          provider-id: callback.do
          app-id: 100550231
          app-secret: 69b6ab57b22f3c2fe6a6149274e3295e

       wx:
          provider-id: wx
          app-id: wxd99431bbff8305a0
          app-secret: 60f78681d063590a469f1b297feff3c4
    oauth2:
      clients:
        - {client-id: qiaolin, client-secret: qiaolinsecret, access-token-validity-seconds: 7200}
        - {client-id: test, client-secret: test}
server:
  port: 80
  # session 超时时间
  session:
    timeout: 600

# 现在不需要这个了
#security:
#  oauth2:
#    client:
#      client-id: qiaolin
#      client-secret: qiaolinsecret

