spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/security-study?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password:

  session:
    store-type: none

logging:
  level:
   indi.qiaolin.security: debug

# 不启用权限认证
# security:
#   basic:
#     enabled: false



